Controllers/GiderlerController.cs
using Mecom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class GiderlerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Giderler
        public ActionResult Index()
        {
            ViewBag.purchaseInvoiceId = new SelectList(db.PurchaseInvoices, "id", "explanation");
            return View();
        }

        public ActionResult GiderEkle(Payment p)
        {
            var pur = db.PurchaseInvoices.Find(p.purchaseInvoiceId);
            pur.amount += p.amount;
            db.Entry(pur).State = System.Data.Entity.EntityState.Modified;
            db.Payments.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GiderDuzenle(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = db.Payments.Find(id);
            if(p == null)
            {
                return HttpNotFound();
            }
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GiderDuzenle(Payment p)
        {
            if (ModelState.IsValid)
            {
                db.Payments.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public ActionResult GiderSil(int? id)
        {
            Payment p = db.Payments.Find(id);
            db.Payments.Remove(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult GetAllPayment()
        {
            var p = db.Payments.ToList();
            return PartialView("~/Views/Giderler/_GetAllPaymentPartial.cshtml", p);
        }
    }
}

Controllers/GuncelController.cs
using Mecom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class GuncelController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        int odenmemisFatura;
        int odenmisFatura;
        int gecikmisFatura;
        double topSat = 0;
        double topAl = 0;

        public ActionResult Index()
        {
            getStats();
            ViewBag.odenmemis = odenmemisFatura;
            ViewBag.gecikmis = gecikmisFatura;
            ViewBag.odenmis = odenmisFatura;

            ViewBag.topgel = topSat;
            ViewBag.topgid= topAl;
            ViewBag.satis = db.Assets.Count();
            ViewBag.alis = db.Payments.Count();
            ViewBag.calisan = db.Staffs.Count();
            ViewBag.musteri = db.Customers.Count();
            ViewBag.tedarikci = db.Suppliers.Count();
         
            return View();
        }

        public void getStats()
        {

            // Ödenmemiş gider faturaları
            var odenmemis = from p in db.PurchaseInvoices
                            where p.isPaid == false
                            select p;
            odenmemisFatura = odenmemis.Count();

            // Ödenmiş gider faturaları
            var odenmis = from o in db.PurchaseInvoices
                          where o.isPaid == true
                          select o;
            odenmisFatura = odenmis.Count();

            // Gecikmiş gider faturaları
            var gecikmis = from ge in db.PurchaseInvoices
                           where ge.lastPaymentDate.Month > DateTime.Now.Month || ge.lastPaymentDate.Day > DateTime.Now.Day
                           || ge.lastPaymentDate.Month == DateTime.Now.Month && ge.lastPaymentDate.Day > DateTime.Now.Day
                           select ge;
            gecikmisFatura = gecikmis.Count();

            // Toplam gelir
            if(db.Assets.FirstOrDefault() != null)
            {
                topSat = db.Assets.Sum(o => o.services.price);
            } 
                

            // Toplam gider
            foreach (var p in db.Payments)
            {
                topAl += p.amount;
            }
        }

        public ActionResult err()
        {
            return View();
        }

        public bool isLate(PurchaseInvoice p)
        {
            int mouth = p.lastPaymentDate.Month;
            int day = p.lastPaymentDate.Day;
            int year = p.lastPaymentDate.Year;

            bool result;
            if (mouth > DateTime.Now.Month || day > DateTime.Now.Day)
                result = false;
            else
                result = true;

            return result;
        }
    }
}

Controllers/RaporlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class RaporlarController : Controller
    {
        // GET: Raporlar
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SatislarController.cs
using Mecom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class SatislarController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Satislar
        public ActionResult Index()
        {
            ViewBag.billOfSaleId = new SelectList(db.BillOfSales, "id", "explanation");
            ViewBag.customerId = new SelectList(db.Customers, "id", "fullName");
            ViewBag.servicesId = new SelectList(db.Servicies, "id", "name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SatisEkle(Asset a)
        {
            if(ModelState.IsValid)
            {
                var i = db.BillOfSales.Find(a.billOfSaleId);
                var s = db.Servicies.Find(a.servicesId);
                i.amount += s.price;
                db.Entry(i).State = System.Data.Entity.EntityState.Modified;
                db.Assets.Add(a);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.billOfSaleId = new SelectList(db.BillOfSales, "id", "explanation");
            ViewBag.customerId = new SelectList(db.Customers, "id", "fullName");
            ViewBag.servicesId = new SelectList(db.Servicies, "id", "name", "price");
            return View(a);
        }

        public ActionResult SatisSil(int? id)
        {
            Asset a = db.Assets.Find(id);
            var i = db.BillOfSales.Find(a.billOfSaleId);
            var s = db.Servicies.Find(a.servicesId);
            i.amount -= s.price;
            db.Assets.Remove(a);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDuzenle(int? id)
        {
            ViewBag.customerId = new SelectList(db.Customers, "id", "fullName");
            ViewBag.servicesId = new SelectList(db.Servicies, "id", "name");
            if (id ==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var a = db.Assets.Find(id);
            if(a == null)
            {
                return HttpNotFound();
            }
            return View(a);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SatisDuzenle([Bind(Include = "id,amount,customerId,servicesId,isPaid")] Asset a)
        {
            if(ModelState.IsValid)
            {
                db.Entry(a).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(a);
        }

        [ChildActionOnly]
        public ActionResult GetAllAsset()
        {
            var a = db.Assets.ToList();
            return PartialView("~/Views/Satislar/_GetAllAssetPartial.cshtml", a);
        }

        public JsonResult GetAllAssetJson()
        {
            var assetList = db.Assets.ToList();
            return Json(assetList, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MeCom</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            background-image:url(http://represent.de/img/background.jpg);
        }

        .llg {
            padding: 20px;
            border-radius: 3px;
            width: 400px;
            margin: 0 auto;
            margin-top: 30px;
            text-align:center;
            background: white;
            -webkit-box-shadow: 0px 0px 83px -8px rgba(0,0,0,0.75);
            -moz-box-shadow: 0px 0px 83px -8px rgba(0,0,0,0.75);
            box-shadow: 0px 0px 83px -8px rgba(0,0,0,0.75);
        }

        .logoo {
            margin-bottom: 20px;
        }

        .form-control {
            display: inline;
        }
        input, select, textarea {
            display:inline-block;
        }



    </style>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MeCom</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Anasayfa")</li>
                    <li>@Html.ActionLink("Hakkında", "Hakkinda", "Anasayfa")</li>
                    <li>@Html.ActionLink("İletişim", "Iletisim", "Anasayfa")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mecom</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_PanelLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MeCom</title>
    @Styles.Render("~/Content/panel")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="@Url.Action("Index","Guncel")">
                            <img alt="Brand" src="~/images/mecomLogo.png" id="logo" />
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">@DateTime.Now.ToString("D") 
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                 @User.Identity.GetUserName() </a></li>
                        </ul>
                </div>
              </div>
            </nav>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-3 col-md-2" id="panelMenu" style="padding-right:0px">   
                    <ul class="nav nav-pills nav-stacked" style="width:100%">
                        <li><a href="@Url.Action("Index", "Guncel")"><span class="glyphicon glyphicon-fire"> Güncel Durum</span></a></li>
                        <li><a href="@Url.Action("Index", "Satislar")"><span class="glyphicon glyphicon-log-in"> Satışlar</span></a></li>
                        <li><a href="@Url.Action("Index", "Giderler")"><span class="glyphicon glyphicon-log-out"> Giderler</span></a></li>
                        <li><a href="@Url.Action("Index", "Calisanlar")"><span class="glyphicon glyphicon-user"> Çalışanlar</span></a></li>
                        <li><a href="@Url.Action("Index", "Musteriler")"><span class="glyphicon glyphicon-list"> Müşteriler</span></a></li>
                        <li><a href="@Url.Action("Index", "Tedarikciler")"><span class="glyphicon glyphicon-shopping-cart"> Tedarikçiler</span></a></li>
                        <li><a href="@Url.Action("Index", "Servisler")"><span class="glyphicon glyphicon-tags"> Hizmeter - Ürünler</span></a></li>
                        <li><a href="@Url.Action("AlimFaturasi", "Faturalar")"><span class="glyphicon glyphicon-list-alt"> Alım Faturası</span></a></li>
                        <li><a href="@Url.Action("SatisFaturasi", "Faturalar")"><span class="glyphicon glyphicon-list-alt"> Satış Faturası</span></a></li>
                        <li><a href="@Url.Action("Index", "Raporlar")"><span class="glyphicon glyphicon-stats"> Raporlar</span></a></li>
                    </ul>
                    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
                </div>
            <div class="col-xs-12 col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>