Controllers/CalisanlarController.cs
using Mecom.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class CalisanlarController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Calisanlar

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CalisanEkle(Staff s)
        {
            db.Staffs.Add(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CalisanSil(int? id)
        {
            Staff s = db.Staffs.Find(id);
            db.Staffs.Remove(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CalisanDuzenle(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var s = db.Staffs.Find(id);
            if(s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CalisanDuzenle([Bind(Include = "id,Name,lastName,phone,email,profession,salary")] Staff s)
        {
            if(ModelState.IsValid)
            {
                db.Entry(s).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(s);
        }

        [ChildActionOnly]
        public ActionResult GetAllStaff()
        {
            return PartialView("~/Views/Calisanlar/_GetAllStaff.cshtml");
        }

        public JsonResult GetAllStaffJson()
        {
            var staffList = db.Staffs.ToList();
            return Json(staffList, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Calisanlar/CalisanDuzenle.cshtml
@model Mecom.Models.Staff
@{
    ViewBag.Title = "Çalışan Düzenle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}


@using (Html.BeginForm("CalisanDuzenle","Calisanlar"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Çalışan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Git", "Index")
</div>

Views/Calisanlar/Index.cshtml
@model Mecom.Models.Staff
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Çalışanlar";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h3 style="text-align:center">Çalışanlar</h3>
<div ng-app="SearchApp" ng-controller="staffSearchController">
    <div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-primary" data-toggle="modal" data-target=".addStaff" type="button">Çalışan Ekle</button>
        </span>
        <input type="text" class="form-control" ng-model="searchText" placeholder="Ara..." />
    </div>

    <br />

    <div class="modal fade addStaff" tabindex="-1" role="dialog" aria-labelledby="AddStaff">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                @using (Html.BeginForm("CalisanEkle", "Calisanlar"))
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Müşteri Ekle</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", maxLength = "10", required = "required" } })
                                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", maxLength = "80", type = "email", required = "required" } })
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.profession, htmlAttributes: new { @class = "control-label col-md-4", maxLength = "80" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.profession, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.profession, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-4", maxLength = "80" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.userId, new { htmlAttributes = new { @class = "form-control", @Value = User.Identity.GetUserId() } })

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-7">
                                <input type="submit" value="Kaydet" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    @Html.Action("GetAllStaff")
</div>

Views/Calisanlar/_GetAllStaff.cshtml
@model Mecom.Models.Staff

<div class="row">
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(m => m.Name)</th>
            <th>@Html.DisplayNameFor(m => m.lastName)</th>
            <th>@Html.DisplayNameFor(m => m.email)</th>
            <th>@Html.DisplayNameFor(m => m.phone)</th>
            <th>@Html.DisplayNameFor(m => m.profession)</th>
            <th>@Html.DisplayNameFor(m => m.salary)</th>
            <th colspan="2">İşlemler</th>
        </tr>
        <tr ng-repeat="s in staffs | filter:searchText">
            <td>{{ s.Name }}</td>
            <td>{{ s.lastName }}</td>
            <td>{{ s.email }}</td>
            <td>{{ s.phone }}</td>
            <td>{{ s.profession }}</td>
            <td>{{ s.salary }}</td>
            <td><a href="@Url.Action("CalisanSil","Calisanlar")\{{ s.id }}"><span class="glyphicon glyphicon-trash"></span></a></td>
            <td><a href="@Url.Action("CalisanDuzenle","Calisanlar")\{{ s.id }}"><span class="glyphicon glyphicon-edit"></span></a></td>
        </tr>
    </table>
</div>