Controllers/TedarikcilerController.cs
using Mecom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class TedarikcilerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Tedarikci
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TedarikciEkle(Supplier s)
        {
            db.Suppliers.Add(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TedarikciSil(int? id)
        {
            Supplier s = db.Suppliers.Find(id);
            db.Suppliers.Remove(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TedarikciDuzenle(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var s = db.Suppliers.Find(id);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TedarikciDuzenle([Bind(Include = "id,companyName,phone,email,adress")] Supplier s)
        {
            if (ModelState.IsValid)
            {
                db.Entry(s).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(s);
        }

        [ChildActionOnly]
        public ActionResult GetAllSupplier()
        {
            return PartialView("~/Views/Tedarikciler/_GetAllSupplierPartial.cshtml");
        }

        public JsonResult GetAllSupplierJson()
        {
            var supplierList = db.Suppliers.ToList();
            return Json(supplierList, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Tedarikciler/Index.cshtml
@model Mecom.Models.Supplier
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Tedarikçiler";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h3 style="text-align:center">Tedarikçiler</h3>
<div ng-app="SearchApp" ng-controller="supplierSearchController">
    <div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-primary" data-toggle="modal" data-target=".addSupplier" type="button">Tedarikçi Ekle</button>
        </span>
        <input type="text" class="form-control" ng-model="searchText" placeholder="Ara..." />
    </div>


    <br />

    <div class="modal fade addSupplier" tabindex="-1" role="dialog" aria-labelledby="AddSupplier">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                @using (Html.BeginForm("TedarikciEkle", "Tedarikciler"))
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Müşteri Ekle</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.adress, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.adress, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.adress, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", maxLength = "10", required = "required" } })
                                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", maxLength = "80", type = "email", required = "required" } })
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.userId, new { htmlAttributes = new { @class = "form-control", @Value = User.Identity.GetUserId() } })

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-7">
                                <input type="submit" value="Kaydet" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>        
</div>
    @Html.Action("GetAllSupplier")
</div>

Views/Tedarikciler/TedarikciDuzenle.cshtml
@model Mecom.Models.Supplier

@{
    ViewBag.Title = "Tedarikçi Duzenle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tedarikçi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Git", "Index")
</div>

Views/Tedarikciler/_GetAllSupplierPartial.cshtml
@model Mecom.Models.Supplier

<div class="row">
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(m => m.companyName)</th>
            <th>@Html.DisplayNameFor(m => m.adress)</th>
            <th>@Html.DisplayNameFor(m => m.email)</th>
            <th>@Html.DisplayNameFor(m => m.phone)</th>
            <th colspan="2">İşlemler</th>
        </tr>
        <tr ng-repeat="s in suppliers | filter:searchText">
            <td>{{ s.companyName }}</td>
            <td>{{ s.adress }}</td>
            <td>{{ s.email }}</td>
            <td>{{ s.phone }}</td>
            <td><a href="@Url.Action("TedarikciSil","Tedarikciler")\{{ s.id }}"><span class="glyphicon glyphicon-trash"></span></a></td>
            <td><a href="@Url.Action("TedarikciDuzenle","Tedarikciler")\{{ s.id }}"><span class="glyphicon glyphicon-edit"></span></a></td>
        </tr>
    </table>
</div>