Controllers/MusterilerController.cs
using Mecom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Mecom.Controllers
{
    public class MusterilerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Musteriler
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MusteriEkle(Customer c)
        {
            db.Customers.Add(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSil(int? id)
        {
            Customer c = db.Customers.Find(id);
            db.Customers.Remove(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriDuzenle(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var c = db.Customers.Find(id);
            if(c == null)
            {
                return HttpNotFound();
            }
            return View(c);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MusteriDuzenle([Bind(Include = "id,name,lastName,email,phone,companyName")] Customer c)
        {
            if(ModelState.IsValid)
            {
                db.Entry(c).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);
            
        }


        [ChildActionOnly]
        public ActionResult GetAllCustomer()
        {
            return PartialView("~/Views/Musteriler/_GetAllCustomer.cshtml");
        }

        public JsonResult GetAllCustomerJson()
        {
            var customerList = db.Customers.ToList();
            return Json(customerList, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Musteriler/Index.cshtml
@model Mecom.Models.Customer
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Müşteriler";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<h3 style="text-align:center">Müşteriler</h3>

<div ng-app="SearchApp" ng-controller="customerSearchController">
    <div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-primary" data-toggle="modal" data-target=".addCustomer" type="button">Müşteri Ekle</button>
        </span>
        <input type="text" class="form-control" ng-model="searchText" placeholder="Ara..." />
    </div>

    <br />

    <div class="modal fade addCustomer" tabindex="-1" role="dialog" aria-labelledby="AddCustomer">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                @using (Html.BeginForm("MusteriEkle", "Musteriler"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Müşteri Ekle</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", maxLength = "50", required = "required" } })
                                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", maxLength = "10", required = "required" } })
                                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", maxLength = "80", type = "email", required = "required" } })
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-4", maxLength = "80" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.userId, new { htmlAttributes = new { @class = "form-control", @Value = User.Identity.GetUserId() } })

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-7">
                                <input type="submit" value="Kaydet" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    @Html.Action("GetAllCustomer")
</div>

Views/Musteriler/MusteriDuzenle.cshtml
@model Mecom.Models.Customer

@{
    ViewBag.Title = "MusteriDuzenle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Müşteri</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

Views/Musteriler/_GetAllCustomer.cshtml
@model Mecom.Models.Customer

<div class="row" >
    <table class="table" id="searchTextResult">
        <tr>
            <th>@Html.DisplayNameFor(m => m.name)</th>
            <th>@Html.DisplayNameFor(m => m.lastName)</th>
            <th>@Html.DisplayNameFor(m => m.phone)</th>
            <th>@Html.DisplayNameFor(m => m.email)</th>
            <th colspan="2">İşlemler</th>
        </tr>
        <tr ng-repeat="c in customers | filter:searchText">
            <td>{{ c.name }}</td>
            <td>{{ c.lastName }}</td>
            <td>{{ c.phone }}</td>
            <td>{{ c.email }}</td>
            <td><a href="@Url.Action("MusteriSil","Musteriler")\{{ c.id }}"><span class="glyphicon glyphicon-trash"></span></a></td>
            <td><a href="@Url.Action("MusteriDuzenle","Musteriler")\{{ c.id }}"><span class="glyphicon glyphicon-edit"></span></a></td>
        </tr>
    </table> 
</div>